repos:
  -  repo: https://github.com/asottile/pyupgrade
     rev: v2.31.0
     hooks:
       -  id: pyupgrade
          args: ["--py38-plus"]

  - repo: https://github.com/adamchainz/django-upgrade
    rev: '1.4.0'
    hooks:
      - id: django-upgrade
        args: [--target-version, "3.2"]

  - repo: https://github.com/PyCQA/flake8
    rev: 4.0.1
    hooks:
      - id: flake8
        additional_dependencies:
          - flake8-broken-line
          - flake8-bugbear
          - flake8-builtins
          - flake8-coding
          - flake8-commas
          - flake8-comprehensions
          - flake8-eradicate
          - flake8-quotes
          - flake8-tidy-imports
          - pep8-naming

  - repo: https://github.com/pycqa/isort
    rev: 5.10.1
    hooks:
      - id: isort

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.1.0
    hooks:
      - id: check-added-large-files
      - id: check-case-conflict
      - id: check-json
      - id: check-merge-conflict
      - id: check-symlinks
      - id: end-of-file-fixer
      - id: trailing-whitespace
