# Generated by Django 2.2.4 on 2019-09-26 08:35

import django.db.models.deletion
from django.db import migrations, models

import djangocms_attributes_field.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cms', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestPlugin',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='test_app_testplugin', serialize=False, to='cms.CMSPlugin')),
                ('label', models.CharField(max_length=255, verbose_name='Test app label')),
                ('attributes1', djangocms_attributes_field.fields.AttributesField(default=dict)),
                ('attributes2', djangocms_attributes_field.fields.AttributesField(default=dict)),
            ],
            options={
                'abstract': False,
            },
            bases=('cms.cmsplugin',),
        ),
    ]
